version: '3.9'
services:
  backend:
    build: ./backend
    container_name: ai-agent-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  # Mount app code for hot reload
      - ./backend/agents:/app/agents
      - ./models:/root/.cache
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipassword
      POSTGRES_DB: aiproject
      GROQ_API_KEY: ${GROQ_API_KEY}
      DEEPGRAM_API_KEY: ${DEEPGRAM_API_KEY}
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: ai-agent-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Mount entire frontend directory
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker

  db:
    image: postgres:15
    container_name: ai-agent-db
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipassword
      POSTGRES_DB: aiproject
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local